- ros_topic_name: /bluerov/odom
  gz_topic_name: /model/bluerov/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /bluerov/dvl/velocity
  gz_topic_name: /model/bluerov/dvl/velocity
  ros_type_name: dave_interfaces/msg/DVL
  gz_type_name: gz.msgs.DVL
  direction: GZ_TO_ROS
